stages:
  - publish_artifact
  
publish_job:
  stage: publish_artifact
  variables:
    ARTIFACTORY_BASE_URL: https://artifactory.push.tools.roku.com/artifactory
    REPO_NAME: genericrepo/ads/bazel/rules_jvm_external
    ARTIFACT_NAME: rules_jvm_external-$CI_COMMIT_SHA
  script:
    - git archive --prefix $ARTIFACT_NAME/  HEAD --format zip > "$ARTIFACT_NAME".zip
    - curl -f -u "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" -X PUT "${ARTIFACTORY_BASE_URL}/${REPO_NAME}/${ARTIFACT_NAME}.zip" -T "${ARTIFACT_NAME}.zip"
  tags:
    - bazeldev
