stages:
  - publish_artifact
  
publish_job:
  stage: publish_artifact
  image: plan/jfrog-cli
  variables:
    ARTIFACTORY_BASE_URL: https://artifactory.push.tools.roku.com
    ARTIFACT_NAME: rules_jvm_external
    REPO_NAME: genericrepo/ads/bazel/rules_jvm_external
  script:
    - curl -fL https://install-cli.jfrog.io | sh
    - jf config add $JFROG_PLATFORM_SERVER_ID--url=$JFROG_PLATFORM_URL --user=$JFROG_PLATFORM_USER --password=$JFROG_PLATFORM_PASS
    - tar -czvf "rules_jvm_external-$CI_COMMIT_SHA.zip" .
    - jf rt u "rules_jvm_external-$CI_COMMIT_SHA.zip" "$REPO_NAME"/"rules_jvm_external-$CI_COMMIT_SHA.zip" --recursive=false