image: gradle:latest
 
before_script:
 # Download JFrog CLI
 -  curl -fL https://install-cli.jfrog.io | sh
 # configure artifactory server
 - jf config add $JFROG_PLATFORM_SERVER_ID--url=https://artifactory.push.tools.roku.com/ui/repos/tree/General/genericrepo --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD
 - jf config show
 
 # configure gradle, set upload and download repos
 - jf gradlec --repo-resolve $JFROG_PLATFORM_REPO --repo-deploy $JFROG_PLATFORM_REPO
 
gitlab-ci-gradle-build: #This job name will be used as the build info repository name in artifactory
 stage: build
 script:
   # upload the built artifact to artifactory
   - jf gradle clean artifactoryPublish --build-name=$CI_JOB_NAME --build-number=$CI_JOB_ID
   # Collect environment variables for the build
   - jf rt bce $CI_JOB_NAME $CI_JOB_ID
   # Collect VCS details from git and add them to the build
   - jf rt bag $CI_JOB_NAME $CI_JOB_ID
   # Publish build info
   - jf rt bp $CI_JOB_NAME $CI_JOB_ID
   # Scan with xray
   - jf bs $CI_JOB_NAME $CI_JOB_ID